services:
  goauth:
    container_name: goauth
    build:
      context: .
      dockerfile: Dockerfile
    image: goauth:latest

    ports:
      - "8080:8080"

    environment:
      APP_ENV: production
      PORT: 8080
    volumes:
      - ./:/app
      - /app/tmp
    restart: unless-stopped

